name: Analyze branch
on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: solutelabs-runner

    steps:
      - name: Setup sonar scanner
        uses: warchant/setup-sonar-scanner@v3

      - name: 'Checkout repository on branch: ${{ github.REF }}'
        uses: actions/checkout@v2
        with:
          ref: ${{ github.REF }}
          fetch-depth: 0

      # Conditional execution can be done, in this case the parameter to use with sonar scanner are different if we are analyzing master or a branch
      - if: endsWith(github.REF, '/master') == true
        name: 'Run an analysis of the ${{ github.REF }} branch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        
        run: sonar-scanner
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.branch.name=${GITHUB_REF:11}
          -Dsonar.scm.provider=git